version: '3.9'
services:
    db:
        image: mysql:5.7
        container_name: cursos-db
        hostname: db
        restart: always
        ports:
            - "3306:3306"
        environment:
            #MYSQL_ROOT_PASSWORD: changeme
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_USER: user
            MYSQL_PASSWORD: changeme
            MYSQL_DATABASE: gultalks
        volumes:
            - .:/docker-entrypoint-initdb.d
        networks:
            cursos:
                 ipv4_address: 172.16.238.3
    
    web:
        build: .
        container_name: cursos-web
        hostname: web
        entrypoint: ./docker-entrypoint.sh
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes: 
            - ".:/app"
        links:
            - db:db
        depends_on:
            - db
        ports:
            - "3000:3000"
        networks:
            cursos:
                ipv4_address: 172.16.238.2
        environment:
            DB_USER: user
            DB_NAME: gultalks
            DB_PASSWORD: changeme
            DB_HOST: db
            
networks:
    cursos:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
                  gateway: 172.16.238.1
