# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18041db982a1fab3b0af5424ea89c9033ccc373222966741fb06a52d3789d82e32f59a5fc9f078c58a8961bb84a6448d88dff1cbc758b3f6941da00333f311fa
  recaptcha_public_key: 6Lck_vcSAAAAAOL68XYHkVnbVMPDY7mgd1wtX8_r
  recaptcha_private_key: 6Lck_vcSAAAAAA476ajDHhYEjL9uAUzcA9mlRBUB
  recaptcha_proxy: localhost:3000

test:
  secret_key_base: 7003fd21fd3a2c2637d671bf4b7543d23af06015e104a0024052f6f03aae3f4ce2c94b5ac17085f18a7cf4c887fa218cd8300e0a30692b2ca4aaa1a01251c32c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
