# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18041db982a1fab3b0af5424ea89c9033ccc373222966741fb06a52d3789d82e32f59a5fc9f078c58a8961bb84a6448d88dff1cbc758b3f6941da00333f311fa
  session_secret: ee401aa08bdf82ba33779b4918461cfd6d1f2e79c9d477bb1fa5db69da34a33302f802c6432f470dbbd1d927046be8ab65f887000252b5612db5cff2c2183424
  recaptcha_public_key: 6Lck_vcSAAAAAOL68XYHkVnbVMPDY7mgd1wtX8_r
  recaptcha_private_key: 6Lck_vcSAAAAAA476ajDHhYEjL9uAUzcA9mlRBUB
  recaptcha_proxy: localhost:3000
  host: "development.com"
  bitly_user: "dsiz"
  bitly_key: "R_ef87541ba56a4f889a744083adab3443"
  devise_secret_key: "1b4fe696e90ff45ce7b08eec8c2a69c10d7a61655354f4617995ed87c9af0d32861c244eaa9a3a7cf9796022260b0ffb7da38d2ec5c850cb0432bda262362932"

test:
  secret_key_base: 7003fd21fd3a2c2637d671bf4b7543d23af06015e104a0024052f6f03aae3f4ce2c94b5ac17085f18a7cf4c887fa218cd8300e0a30692b2ca4aaa1a01251c32c
  recaptcha_public_key: 6Lck_vcSAAAAAOL68XYHkVnbVMPDY7mgd1wtX8_r
  recaptcha_private_key: 6Lck_vcSAAAAAA476ajDHhYEjL9uAUzcA9mlRBUB
  recaptcha_proxy: localhost:3000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  mailer:
    address: <%= Figaro.env.email_address %>
    port: <%= Figaro.env.email_port %>
    user: <%= Figaro.env.email_user %>
    password: <%= Figaro.env.email_password %>
  host: <%= Figaro.env.host %>
  secret_key_base: <%= Figaro.env.secret_key_base %>
  recaptcha_public_key: <%= Figaro.env.recaptcha_public_key %>
  recaptcha_private_key: <%= Figaro.env.recaptcha_private_key %>
  recaptcha_proxy: <%= Figaro.env.recaptcha_proxy %>
  bitly_user: <%= Figaro.env.bitly_user %>
  bitly_key: <%= Figaro.env.bitly_key %>
  devise_secret_key: <%= Figaro.env.devise_secret_key %>
  
  secret_key: <%= Figaro.env.secret_key %>
